name: Deploy Voila App to GitHub Pages

on:
  push:
    branches:
      - main  # 每次推送到main分支时触发

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install voila ipywidgets matplotlib

    - name: Create output directory
      run: |
        mkdir -p ./output  # 创建 output 目录，如果不存在的话

    - name: Run Voila and save the output
      run: |
        voila quadratic_function.ipynb --template=lab --no-browser --port=8888 --output=./output &  # 使用--output指定目录
        sleep 10  # 等待Voila启动

    - name: Set up GitHub authentication
      run: |
        git config --global user.name "tysunseven"  # 替换为你的GitHub用户名
        git config --global user.email "tysun@mail.ustc.edu.cn"  # 替换为你的GitHub邮箱
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git  # 使用GITHUB_TOKEN进行身份验证

    - name: Upload to GitHub Pages
      run: |
        git checkout -b gh-pages  # 切换到gh-pages分支
        cp -r ./output/* ./  # 将Voila的输出复制到当前目录
        git add .
        git commit -m "Deploy Voila app"
        git push --force origin gh-pages  # 使用GITHUB_TOKEN推送到gh-pages分支
