name: Deploy Voila App to GitHub Pages

on:
  push:
    branches:
      - main  # 每次推送到main分支时触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        pip install voila ipywidgets matplotlib
        
    - name: Run Voila and save the output
      run: |
        voila quadratic_function.ipynb --template=lab --no-browser --port=8888 &
        sleep 10  # 等待Voila启动

    - name: Upload to GitHub Pages
      run: |
        git config --global user.name "Your Name"
        git config --global user.email "your-email@example.com"
        git checkout -b gh-pages  # 切换到gh-pages分支
        cp -r /path/to/voila/output/* ./  # 将Voila的输出复制到当前目录
        git add .
        git commit -m "Deploy Voila app"
        git push --force origin gh-pages